# Generated by Django 5.2.7 on 2025-10-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
